# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.


jobs:
  configure_infrastructure:
    docker:
      -  image: python:3.7-alpine3.11
    steps:
      -  add_ssh_keys:
           fingerprints:
             - "ab:a8:74:48:d8:0f:14:c9:97:53:44:8d:cb:aa:ea:35"
      
      -  run:
           name: Install dependencies
           command: |
             apk add --update ansible
      
      -  run:
           name: Configure server
           command: |
             ansible-playbook -i inventory.txt main.yml
         
   
         

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      -  configure_infrastructure
     
